<?php
/**
 * Mapa de traducción de géneros.
 * Clave = nombre en BD (español), Valor = traducción al idioma actual.
 * Si un género no está en el mapa, se muestra tal cual.
 */
function getGenreTranslations(string $lang): array {
    $maps = [
        'es' => [], // español es el idioma base, no necesita traducción
        'en' => [
            'Autoayuda'          => 'Self-help',
            'Aventura'           => 'Adventure',
            'Ciencia Ficción'    => 'Science Fiction',
            'Distopía'           => 'Dystopia',
            'Existencialismo'    => 'Existentialism',
            'Fábula'             => 'Fable',
            'Fantasía'           => 'Fantasy',
            'Filosofía'          => 'Philosophy',
            'Finanzas'           => 'Finance',
            'Historia'           => 'History',
            'Histórico'          => 'Historical',
            'Infantil'           => 'Children',
            'Negocios'           => 'Business',
            'Novela'             => 'Novel',
            'Novela experimental'=> 'Experimental Novel',
            'Psicología'         => 'Psychology',
            'Psicológico'        => 'Psychological',
            'Realismo'           => 'Realism',
            'Realismo mágico'    => 'Magical Realism',
            'Romance'            => 'Romance',
            'Terror'             => 'Horror',
            'Thriller'           => 'Thriller',
            'Clásico'            => 'Classic',
            'Poesía'             => 'Poetry',
            'Drama'              => 'Drama',
            'Misterio'           => 'Mystery',
            'Biografía'          => 'Biography',
            'Pruebas'            => 'Testing',
        ],
        'fr' => [
            'Autoayuda'          => 'Développement personnel',
            'Aventura'           => 'Aventure',
            'Ciencia Ficción'    => 'Science-fiction',
            'Distopía'           => 'Dystopie',
            'Existencialismo'    => 'Existentialisme',
            'Fábula'             => 'Fable',
            'Fantasía'           => 'Fantaisie',
            'Filosofía'          => 'Philosophie',
            'Finanzas'           => 'Finance',
            'Historia'           => 'Histoire',
            'Histórico'          => 'Historique',
            'Infantil'           => 'Jeunesse',
            'Negocios'           => 'Affaires',
            'Novela'             => 'Roman',
            'Novela experimental'=> 'Roman expérimental',
            'Psicología'         => 'Psychologie',
            'Psicológico'        => 'Psychologique',
            'Realismo'           => 'Réalisme',
            'Realismo mágico'    => 'Réalisme magique',
            'Romance'            => 'Romance',
            'Terror'             => 'Horreur',
            'Thriller'           => 'Thriller',
            'Clásico'            => 'Classique',
            'Poesía'             => 'Poésie',
            'Drama'              => 'Drame',
            'Misterio'           => 'Mystère',
            'Biografía'          => 'Biographie',
        ],
        'pt' => [
            'Autoayuda'          => 'Autoajuda',
            'Aventura'           => 'Aventura',
            'Ciencia Ficción'    => 'Ficção Científica',
            'Distopía'           => 'Distopia',
            'Existencialismo'    => 'Existencialismo',
            'Fábula'             => 'Fábula',
            'Fantasía'           => 'Fantasia',
            'Filosofía'          => 'Filosofia',
            'Finanzas'           => 'Finanças',
            'Historia'           => 'História',
            'Histórico'          => 'Histórico',
            'Infantil'           => 'Infantil',
            'Negocios'           => 'Negócios',
            'Novela'             => 'Romance',
            'Novela experimental'=> 'Romance experimental',
            'Psicología'         => 'Psicologia',
            'Psicológico'        => 'Psicológico',
            'Realismo'           => 'Realismo',
            'Realismo mágico'    => 'Realismo mágico',
            'Romance'            => 'Romance',
            'Terror'             => 'Terror',
            'Thriller'           => 'Suspense',
            'Clásico'            => 'Clássico',
            'Poesía'             => 'Poesia',
            'Drama'              => 'Drama',
            'Misterio'           => 'Mistério',
            'Biografía'          => 'Biografia',
        ],
        'de' => [
            'Autoayuda'          => 'Selbsthilfe',
            'Aventura'           => 'Abenteuer',
            'Ciencia Ficción'    => 'Science-Fiction',
            'Distopía'           => 'Dystopie',
            'Existencialismo'    => 'Existentialismus',
            'Fábula'             => 'Fabel',
            'Fantasía'           => 'Fantasy',
            'Filosofía'          => 'Philosophie',
            'Finanzas'           => 'Finanzen',
            'Historia'           => 'Geschichte',
            'Histórico'          => 'Historisch',
            'Infantil'           => 'Kinderbuch',
            'Negocios'           => 'Wirtschaft',
            'Novela'             => 'Roman',
            'Novela experimental'=> 'Experimenteller Roman',
            'Psicología'         => 'Psychologie',
            'Psicológico'        => 'Psychologisch',
            'Realismo'           => 'Realismus',
            'Realismo mágico'    => 'Magischer Realismus',
            'Romance'            => 'Liebesroman',
            'Terror'             => 'Horror',
            'Thriller'           => 'Thriller',
            'Clásico'            => 'Klassiker',
            'Poesía'             => 'Lyrik',
            'Drama'              => 'Drama',
            'Misterio'           => 'Krimi',
            'Biografía'          => 'Biografie',
        ],
    ];
    return $maps[$lang] ?? [];
}

function translateGenre(string $genre, string $lang): string {
    if ($lang === 'es') return $genre;
    $map = getGenreTranslations($lang);
    return $map[$genre] ?? $genre; // si no hay traducción, muestra el original
}
